### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by yconoclast**

### CODE REVIEW

**Comment by addyosmani** [comment]
@XhmikosR I'm personally fine with these updates (minus the nit above), but will defer to you for a call on landing.

**Comment by XhmikosR** [comment]
LGTM since tests pass.

@yconoclast: please rebase and remove the gitignore patch completely.

**Comment by yconoclast** [comment]
@XhmikosR done ;)

**Comment by XhmikosR** [comment]
@yconoclast: that is not a rebase.

**Comment by yconoclast** [comment]
sorry @XhmikosR now it's ok?

**Pull request merged**
