### PR TITLE
Refactor README.md.

### PR DESCRIPTION
**Pull request by XhmikosR**
Remove upstream options and just link to the upstream docs.

/CC @addyosmani for review

### CODE REVIEW

**Comment by giakki** [comment]
You should probably link to the readme for the version you are using over here, for the time being ;)
[This?](https://github.com/giakki/uncss/blob/e9b83631abee2e22f91ea3046284c20c525d1e03/README.md#within-nodejs)

**Comment by XhmikosR** [comment]
True but I plan to merge this along with the new version anyway.

**Comment by XhmikosR** [comment]
BTW, @giakki the best would be https://github.com/giakki/uncss/blob/0.8.1/README.md#within-node but as you know those tags are missing :/ Anyway, it's not a big deal since this will go along with the update.

**Comment by addyosmani** [comment]
LGTM. I assume we're awaiting the new updates to be ready before merging this in?

**Comment by XhmikosR** [comment]
Yeah, I'm waiting for the next stable to test and then update and finally merge this.

/CC @giakki: any ETA?

**Comment by giakki** [comment]
Sorry for the delay, been kinda busy.
0.12 is out!

**Comment by XhmikosR** [comment]
Thanks @giakki. I did one last test and just updated to 0.12.

**Pull request merged**
